// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urhetwvtfmlmvbyndgdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaGV0d3Z0Zm1sbXZieW5kZ2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDY4MjUsImV4cCI6MjA2NjQyMjgyNX0.bpXPqZwoVYG7Alv2KvxRhjWlM-BQ0Y-N58rr0CuWX8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);